spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
  mvc:
    hidden-method:
      filter:
        enabled: 'true'